apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    version: "v1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx_hello
  template:
    metadata:
      labels:
        app: nginx_hello
        role: nginx
        version: "v1.0"
    spec:
      containers:
      - name: nginx-hello
        image: nginx_hello
        ports:
        - containerPort: 80
